package com.solutionpilot.api;

import com.solutionpilot.domain.ApiResponse;
import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@RestController
public class DecisionController {

  @GetMapping("/decisions")
  public ApiResponse<Map<String, Object>> decisions() {
    Map<String, Object> payload = new LinkedHashMap<>();
    payload.put("backend", "Java 11 + Spring Boot 2.7 + Maven");
    payload.put("database", "PostgreSQL + Flyway");
    payload.put("knowledge", "ima Skill + ima knowledge base");
    payload.put("authRoles", Arrays.asList("ADMIN", "USER"));
    payload.put("deferredSources", Arrays.asList("WeCom knowledge community", "local desktop documents", "cloud drive direct access"));
    payload.put("export", "Word/PPT generated by backend templates");
    return ApiResponse.ok(payload);
  }
}
